#!/usr/bin/env node
'use strict';

const { MongoClient } = require('mongodb');
const mysql = require('mysql');
const config = require('./config');

const convertMemberProfile = require('./modules/member-profile');
const convertThreadAndPost = require('./modules/thread-and-post');
const convertAttachment = require('./modules/attachments');
const convertPmMessage = require('./modules/pm-message');

function createConnection(config) {
  return new Promise((resolve, reject) => {
    let mysqlConnecion = mysql.createConnection(config.mysql);
    MongoClient.connect(config.mongo.url, (err, mongoConnection) => {
      if (err) {
        reject(err);
      }

      resolve({
        mysql: mysqlConnecion, 
        mongo: mongoConnection
      });

    });
  });
}

let conns;

createConnection(config).then(_conns => {
  conns = _conns;
  return convertMemberProfile(config, conns);
}).then(() => {
  return convertAttachment(config, conns);
}).then(() => {
  return convertThreadAndPost(config, conns);
}).then(() => {
  return convertPmMessage(config, conns);
}).then(() => {
  console.log("Finished!");
  process.exit(0);
}).catch(err => {
  console.log(err)
});
