#!/usr/bin/env node
'use strict';

const { MongoClient } = require('mongodb');
const mysql = require('mysql');
const config = require('./config');

const convertMemberProfile = require('./modules/member-profile');

function createConnection(config) {
  return new Promise((resolve, reject) => {
    let mysqlConnecion = mysql.createConnection(config.mysql);
    MongoClient.connect(config.mongo.url, (err, mongoConnection) => {
      if (err) {
        reject(err);
      }

      resolve({
        mysql: mysqlConnecion, 
        mongo: mongoConnection
      });

    });
  });
}

createConnection(config).then(conns => {
  return convertMemberProfile(config, conns);
}).then(() => {
  console.log("Finished!");
  process.exit(0);
}).catch(err => {
  console.log(err)
});
